name: 'GitHub Linear Project Template Sync'
description: 'Version control a Linear Project Template from GitHub by syncing it with data from a specified folder in your repository'
author: 'Sebass van Boxel'
branding:
  icon: 'chevrons-right'
  color: 'gray-dark'
inputs:
  project_folder:
    description: 'The folder containing the project files'
    required: true
  linear_team_id:
    description: 'The Linear team ID'
    required: true
  linear_template_id:
    description: 'The Linear template ID'
    required: true
  linear_token: 
    description: 'The Linear API token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
